### PR TITLE
Generate replicates and plots entries from season/site info

### PR DESCRIPTION
**Pull request by dave-mills**
This PR is for the final part of the updates: generating replicates and plot entries for each season. 

- Once a team has setup the site + season entry, and confirmed that the details (replicate count and chosen treatments) are correct, they can generate a plot listing. 
- The requirements are:
 - The number of replictes specified are created. 
 - Each replicate has 1 plot per treatment. The plot ordering is randomised, and no replicate should repeat the same order of plots (unless necessary due to the number of replicates, e.g., if there are 3 treatments, there is a max of 6 different orders, so if there are 7 replicates we must repeat one).

We need human-readable codes for each replicate and each plot. To help with this, I have chosen to add 'site codes' and 'season codes' that the user can manually input. Then, the system should auto-generate the replicate and plot codes.

For example: 
- A season with 4 replicates and 6 treatments (A, B, C, D, E and F); When generate listing is clicked, the following should happen:
 - 4 replicate entries are created. 
 - For each replicate, the 6 treatments are shuffled, and 6 plot entries are created, linked to each treatment in a random order. E.g:
   - A C D B E F;
   - C A F E B D;
   - F D E A C B;
   - C F B D E A;

 ### TODO

- [x] setup site and season code entries
- [x] allow season code to be null (Rhett might suggest not including it for simplicity)
- [x] create replicate entries in generateListing(); with correct codes;
- [x] for on-station sites; automatically link replicates to station_id;
- [x] for on-farm sites; leave location_id null for replicates (to be populated later from farm registration form data* - which we are not going to do in this round of updates)
- [x] randomise order of treatments and generate plot entries (linked to correct replicate and with sensible codes)
- [x] Update Excel export of plot listing to match new structure

### For a future PR (but related to replicate and plot entries)
- confirm that new replicate and plot listing is pulled into the ODK forms correctly

### CODE REVIEW

**Comment by dave-mills** [comment]
Quick note on codes:
- Site code should be required;
- Season code is optional. It is up to the user whether they want to differentiate seasons within the code. (Some might, others might not as they'll only ever do one season at a time at a site). 

- replicate code is automatically generated in the format: `{$siteCode}-{$seasonCode}-#` (with # as an incrementing integer).
- plots are identified using the treatment_code and the 'number' (an incrementing integer that represents the order in which the plots should be planted within the experiment area).

**Comment by dan-tang-ssd** [comment]
I did some testings for site code and season code:

---

1. (SUCCESS) Fill in site code and season code for existing site without them
 - Site 1, with season 1 and season 2
 - Add site code and season code to season 1, site code and season code showed properly. Only site code showed for season 2
 - Add season code to season 2, site code and season code showed properly

---

2. (SUCCESS) Register a new site
 - fill in site code and season code, submit
 - site code and season code showed properly

---

3. (TBC) Add new season
 - season code cannot be modified
 - is it expected behaviour?
 - new season created with same season code (will it become an issue when generating replicates and plots?)


image

image

image

**Comment by dave-mills** [comment]
> (TBC) Add new season
> season code cannot be modified
> is it expected behaviour?
    
No. I've just fixed this, and also cleared the season code field to force the user to enter a new code for the new season. 



>    (ISSUE) Generate listing for a season with site code and season code
> error occurred
> error message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'location_type' cannot be null (SQL:...
>  um... do I need to define location_type first?

Ooh, yes. I only tested for on-station trials (where the location is linked right away). For on-farm, the location gets linked only after the farms are registered, so for a time the location_id and location_type will be empty. I'd set location_id to nullable, but not location_type. Fixed with a new migration in the latest commit :)

**Comment by dan-tang-ssd** [comment]
> > (TBC) Add new season
> > season code cannot be modified
> > is it expected behaviour?
> 
> No. I've just fixed this, and also cleared the season code field to force the user to enter a new code for the new season.

Tested that the fix will clear season code in "Add new season". A new season can be created by filling in season code.

One potential issue may need to prevent, user may enter a season code which is already existed.
Then we will have two seasons with same site code and season code...

Can we add an unique index to prevent this in database level?
For better user expererence, we may need to detect this in Laravel level and show error message to user in a nicer way...

image

image

image

**Comment by dave-mills** [comment]
> One potential issue may need to prevent, user may enter a season code which is already existed.

Yeah, that's a good idea. I think we can do something with the Laravel Validation rules - we can't just set it as unique, because we need the combo of team_id / site_code / season_code to be unique. But I bet there's either an existing validation rule for that, or we can write a custom one.

**Comment by dan-tang-ssd** [comment]
Generate Listing

On-Farm

```
No.		Result		Site Code		Season Code
======================================================================================
1		Success		TT1-S1			SEA1
2		Success		TT1-S2			N/A
3		Success		N/A			N/A
4		N/A		N/A			SEA1
5		Success 	TT1-S1			SEA3 (has duplicate entry)
```

For case 3
Replicates can be generated without site code and season code.
Validation already added to make sure site code must be entered when create / edit a site / season.
Will we have existing sites without site code appear in the new staging env?

For case 4
Unable to prepare the setup in front end. As it is not possible to enter season code without entering site code

For case 5
Two separate randomized replicates can be generated for two seasons with same site code and same season code.
It is recommended to prevent same site code and season code, as this will create possible confusion when reviewing data.

**Comment by dave-mills** [comment]
Hmm - site code should be required... I'll take a look after lunch

**Comment by dan-tang-ssd** [comment]
On-Station

The testing result for "On-station" is identical to "On-farm"

```
No.		Result		Site Code		Season Code
======================================================================================
1		Sucsses		S12			SEA1
2		Success		S11			N/A
3		Success		N/A			N/A
4		N/A		N/A			SEA1
5		Success		S12			SEA1 (has duplicate entry)

```
For case 3
Replicates can be generated without site code and season code.
Validation already added to make sure site code must be entered when create / edit a site / season.
Will we have existing sites without site code appear in the new staging env?

For case 4
Unable to prepare the setup in front end. As it is not possible to enter season code without entering site code

For case 5
Two separate randomized replicates can be generated for two seasons with same site code and same season code.
It is recommended to prevent same site code and season code, as this will create possible confusion when reviewing data.

**Comment by dave-mills** [comment]
> Will we have existing sites without site code appear in the new staging env?

No, there should be no sites without a code. It is in fact not null in the database, as well as being required through the front-end. I don't think there's a reason to need to test cases where a site has no code?

**Comment by dave-mills** [comment]
> Two separate randomized replicates can be generated for two seasons with same site code and same season code.
It is recommended to prevent same site code and season code, as this will create possible confusion when reviewing data.

I've added a pair of custom validation rules, one for site code and one for season code. The logic is:

1. The site code should be unique *within a team*. 
  - The `UniqueSiteCode` rule checks this is the case and returns a validation error if not.
2. If season codes are not null, they should be unique *within a site*.
  - The `UniqueSeasonCode` rule checks this is the case.

So, we could have:

team_id | site_code | season_code
-|-|-
1 | S1 | 1
1 | S1 | 2
1 | S2 | NULL
1 | S2 | NULL

From this setup: 
- if team 1 added a new site with code="S1", it would be invalid.
- if team 1 added a new season to S1 with season_code = 1, it would be invalid.

(Yes, the NULL season IDs are not ideal; but I don't want to force users to enter a season_id, as teams may not be setup for that. The codes are for human identification of replicates, and when merging data programatically we will continue to use the ids (which are unique). Given there can only be 1 'active' season in a site at any point, there won't be an issue of code clash for active replicates. (And for final datasets, it's easy enough to include season start date to identify them). 

But, of course, if the FAO teams like the idea of Season codes, we are now setup to enforce uniqueness :)

What do you think? 

CleanShot 2022-09-02 at 16 07 57
CleanShot 2022-09-02 at 16 08 13

**Comment by dan-tang-ssd** [comment]
Thank you Dave for adding the validation.

It works well when adding a new site / season.

I found that there is an issue when editing existing site / season.
It returns error when site code is already existed in database. (Yes, sure, we can only edit an existing site)
Not sure whether Laravel has a simple way to tackle this without the record itself in update...

image

image

**Comment by dave-mills** [comment]
>I found that there is an issue when editing existing site / season.
>It returns error when site code is already existed in database. (Yes, sure, we can only edit an existing site)
>Not sure whether Laravel has a simple way to tackle this without the record itself in update...

Oooh, good spot. Yeah, this is also an issue with the default "unique"  validation in Laravel... but there are ways to get round it. I've added a check so that if the site_id / season_id ('id' in the request) exists, then it skips that ID when checking through sites / seasons for duplicates.

**Comment by dan-tang-ssd** [comment]
> > I found that there is an issue when editing existing site / season.
> > It returns error when site code is already existed in database. (Yes, sure, we can only edit an existing site)
> > Not sure whether Laravel has a simple way to tackle this without the record itself in update...
> 
> Oooh, good spot. Yeah, this is also an issue with the default "unique" validation in Laravel... but there are ways to get round it. I've added a check so that if the site_id / season_id ('id' in the request) exists, then it skips that ID when checking through sites / seasons for duplicates.

Thank you Dave for the update.
2 test cases, 1 success but 1 failed.

Success case: Edit site details, do not change site code, submit

Failed case, Edit site details, change site code to another existing code, submit. Site code updated to be the same as another existing site code.

I think we are very very close to success.

image

image

image

**Comment by dan-tang-ssd** [comment]
> > > I found that there is an issue when editing existing site / season.
> > > It returns error when site code is already existed in database. (Yes, sure, we can only edit an existing site)
> > > Not sure whether Laravel has a simple way to tackle this without the record itself in update...
> > 
> > 
> > Oooh, good spot. Yeah, this is also an issue with the default "unique" validation in Laravel... but there are ways to get round it. I've added a check so that if the site_id / season_id ('id' in the request) exists, then it skips that ID when checking through sites / seasons for duplicates.
> 
> Thank you Dave for the update. 2 test cases, 1 success but 1 failed.
> 
> Success case: Edit site details, do not change site code, submit
> 
> Failed case, Edit site details, change site code to another existing code, submit. Site code updated to be the same as another existing site code.
> 
> I think we are very very close to success.
> 
> image
> 
> image
> 
> image

It is now working in my local env.
I think it is good to merge into dev branch.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
