### PR TITLE
Add treatment details

### PR DESCRIPTION
**Pull request by dave-mills**
### Front-end editing of Treatment info for teams

- Added new tab on team editing page to enable management of team treatments. 
CleanShot 2022-08-31 at 15 46 51

- This page lists treatments owned by the team group and treatments owned by the team on 2 separate tables.
- Team group treatments cannot be edited, but the user *can* add 'details' to the treatment - a long text field that is stored in the treatment_details table. Adding a treatment_details record automatically links that record to the current team and chosen treatment. 

- Team treatments can be edited, deleted, and new ones can be created. This uses the same style of Vue components and back end controllers as the Enumerators page.
- All treatments created via this page are automatically linked to the correct team. 

## Site/Season management
(WIP)

When adding a site/season, the user can review the team-specific 'details' for a treatment, and edit them if required. Edits on this page are stored in the seasons table. The season-treatment list is currently stored as JSON, and this update adds treatment_details as a second JSON column in the seasons table. 

- These JSON columns are intended to store the information until the "generate listings" option is chosen by the user. At that point, the JSON columns will be used to generate the `plots` entries that link to the season.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Thank you Dave for the PR.

I did below items to update my local env:
1. Checkout branch "add-treatment-details", git pull to get latest code
2. npm run dev to confirm compilation, then npm run watch
3. Clear browser histroy
4. run migration files
5. Run database seeder files
6. Check and confirm definition data are setup properly, including team group, team, treatment, treatment owner
7. Perform testing

I got a 500 server error when viewing the new treatments tab page for a team:
image

Check Telescope:
image

image

image


Here are my definition data for easy reference:
image

image

image

image

**Comment by dave-mills** [comment]
## Updated site managment:
- Now, when creating a new site; editing a site or creating a new season from an existing site; there is a new interface for picking treatments. This is powered by the LaravelTreatmentCheckboxField vue component, which combines a CheckboxGroup and a set of TextAreas hidden by collapses: 
CleanShot 2022-09-01 at 09 41 16

### Features:

- Any team-specific  details from the `treatment_details` table are pre-populated into the correct textareas. When the list of treatments is retrieved, linked treatment_details are also retrieved through the same request. 
- When editing a site or cloning, if there are existing treatment_details from the season, these override the 'team defaults' pulled from the first request. 

When saving, the site-specific treatment_details are saved to the `seasons` table as a JSON array. 

In  the next update, these will be used to generate the `plots` table entries when a user clicks "Generate Listing". 

This is now ready for checking :)

**Comment by dave-mills** [comment]
Hi Dan,

Ok - from your large array of screenshots, the key piece of information is the text of the 500 error: "Attempt to read property 'treatments' on null". Where is that occuring?

**Comment by dan-tang-ssd** [comment]
> Hi Dan,
> 
> Ok - from your large array of screenshots, the key piece of information is the text of the 500 error: "Attempt to read property 'treatments' on null". Where is that occuring?

C:\public\faw\app\Http\Controllers\Admin\NewTreatmentCrudController.php:97

image

**Comment by dan-tang-ssd** [comment]
> > Hi Dan,
> > Ok - from your large array of screenshots, the key piece of information is the text of the 500 error: "Attempt to read property 'treatments' on null". Where is that occuring?
> 
> C:\public\faw\app\Http\Controllers\Admin\NewTreatmentCrudController.php:97
> 
> image

Thank you Dave! Problem resolved. 
Treatments can be showed when a team not belong to any team group now.

image

**Comment by dan-tang-ssd** [comment]
Test Case 2 - Add a new treatment for a team

Just a very minor thing.

It would be better to have value for columns treatments_owners.created_at and treatments_owners.updated_at after adding a new treatment for a team.

image

image

**Comment by dan-tang-ssd** [comment]
Test case 3 - Show newly added team treatment (required for all sites) in Site Details popup window

Another very minor thing for possible refinement.
Should we display the required team treatment below team group treatments?
i.e. Show RED portion under BLUE portion

image

**Comment by dave-mills** [comment]
> It would be better to have value for columns treatments_owners.created_at and treatments_owners.updated_at after adding a new treatment for a team.

Good spot. Looks like it was because withTimestamps() was on only 1 side of the relationship (so it was populated when we sync treatments to teams, but not when we sync teams to treatments). Fixed in the latest commit.


> Another very minor thing for possible refinement.
> Should we display the required team treatment below team group treatments?

Good idea. The easiest approach is to change the order of merging in the `findPreDefinedTreatments` method. I've done this and now the team group treatments always appear first.

**Comment by dan-tang-ssd** [comment]
Test case 4 - Delete newly created team treatments

Um... This is a question for discussion.

I deleted the newly created team treatments 1001 and 1002.
treatments records deleted, but treatment_owners records remain.
Should we keep treatment_owners records or remove them too?

image

image

**Comment by dan-tang-ssd** [comment]
Test case 5 - Add description to team group treatment

This is a question for discussion.

After adding description to team group treatment, do we need to show them when create / edit a site or season?
When and where do we need to use these metadata?

image

image

**Comment by dave-mills** [comment]
> I deleted the newly created team treatments 1001 and 1002. treatments records deleted, but treatment_owners records remain. Should we keep treatment_owners records or remove them too?

I think in theory; yes, we should do this. But in practice it's not vital, so I think we can leave it as-is for now.

> After adding description to team group treatment, do we need to show them when create / edit a site or season? When and where do we need to use these metadata?

I don't think we need to show the description on the site creation screen - the important part is the team-level details. The description is needed as extra metadata information for when users will eventually download all the collected data, and for teams  / team-groups to reference when planning the studies. I think the current setup is fine for that.

**Comment by dan-tang-ssd** [comment]
I have performed below testings with positive result.
I think it is good to merge this PR into branch "dev".

---

 - Add team treatment, success
 - Add treatment details, success
 - Edit treatment, success
 - Delete treatment, success (confirmed to keep related treatment_owners and treatment_details records)

---

 - Add team treatment in Team A, confirmed that it does not appear in Team B
 - If team treatment is required for every site, treatment showed under group treatments when create / edit a site or season 
 - If team treatment is not required for every site, treatment showed under team treatments when create / edit a site or season
 - treatment details showed in collapsable textarea properly

---

 - Create a new site, modify team treatment description, site specific team treatment description saved and showed properly
 - Edit site, modify team treatment description, site specific team treatment description saved and showed properly
 - Add new season, modify team treatment description, site specific team treatment description saved and showed properly (confirmed that site specific team treatment description are stored in season level)

---

 - Team group treatment, add treatment details, success (confirmed that it is not necessary to show them in site creation screen; confirmed that team specific team group treatment description are stored in team level)

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
